# serverless.yml

service: coins-ohlc-obtener-datos
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  stage: prod
  environment:
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_PORT: ${env:DB_PORT}
      DB_DATABASE: ${env:DB_DATABASE}
      TABLE_COINS_LIST: ${env:TABLE_COINS_LIST}
      NUM_GRUPOS: ${env:NUM_GRUPOS}
      DELAY: ${env:DELAY}
    
functions:
  obtenerOHLC30minutos:
    handler: index.handler
    memorySize: 1024
    name: obtenerOHLC30minutos
    description: LCF6 - Función que toma de la base de datos las criptos, obtiene el OHLC y los pasa a la base de datos.
    timeout: 720
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLCMINS}
      PERIODO: ${env:PERIODOMINS}
    events:
      - eventBridge:
          schedule: cron(0,20,40 11,13,15,17,19,21,23,01,03 ? * * *)
  obtenerOHLC4horas:
    handler: index.handler
    memorySize: 1024
    name: obtenerOHLC4horas
    description: LCF7 - Función que toma de la base de datos las criptos, obtiene el OHLC y los pasa a la base de datos.
    timeout: 720
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLCHORAS}
      PERIODO: ${env:PERIODOHORAS}
    events:
      - eventBridge:
          schedule: cron(0,20,40 15 ? * * *)
  obtenerOHLC4dias:
    handler: index.handler
    memorySize: 1024
    name: obtenerOHLC4dias
    description: LCF8 - Función que toma de la base de datos las criptos, obtiene el OHLC y los pasa a la base de datos.
    timeout: 720
    maximumRetryAttempts: 0
    environment:
      TABLE_OHLC: ${env:TABLE_OHLCDIAS}
      PERIODO: ${env:PERIODODIAS}
    events:
      - eventBridge:
          schedule: cron(0,20,40 15 ? * * *)
